### ISSUE TITLE
`hide_license_risk` doesn't seem to work

### ISSUE THREAD

**Issue by jrieke** [best-of-lists/best-of-generator#25]
**Describe the bug:**

Setting `hide_license_risk: True` in the configuration doesn't seem to have any effect. The ❗️ before the license still shows up.

**Expected behaviour:**

As the docs state, the ❗️ indicator should disappear. 

**Steps to reproduce the issue:**

In projects.yaml:

```yaml
configuration:
  hide_license_risk: True

projects:
  - name: Repo without license
    homepage: https://github.com/jrieke/machine-intelligence
    github_id: jrieke/machine-intelligence
```

Output:

```md
- <b><a href="https://github.com/jrieke/machine-intelligence">Repo without license</a></b> (🥇3 ·  ⭐ 1 · 💀) - Code for the class Machine Intelligence 1 at TU Berlin. <code>❗️Unlicensed</code>
```

**Technical details:**

- Host Machine OS (Windows/Linux/Mac): Mac

**Possible Fix:**

**Additional context:**
