### ISSUE TITLE
Back to top indicator doesn't work if there is no TOC

### ISSUE THREAD

**Issue by jrieke** [best-of-lists/best-of-generator#26]
**Describe the bug:**

The "back to top" indicator (small gray arrow) points to `#content` but this anchor doesn't exist if TOC is turned off.

**Expected behaviour:**

Should still go back to top, maybe insert anchor regardless of TOC or link to title instead.

**Steps to reproduce the issue:**

In projects.yaml:

```yaml
configuration:
  generate_toc: False

projects:
  - name: Any repo
    homepage: https://github.com/best-of-lists/best-of-generator
    github_id: best-of-lists/best-of-generator
```

**Technical details:**

- Host Machine OS (Windows/Linux/Mac): Mac

**Possible Fix:**

**Additional context:**
